### ISSUE TITLE
Changing BODY_HERE to EXCERPT does not save

### ISSUE THREAD

**Issue by seanconklin** [beAutomated/benchmark-email-lite#21] opened 2017-11-18 05:47 UTC
In the Email Template setting, if you replace BODY_HERE with EXCERPT it will not save. Make it so that the failsafe protection will only block saves that do not contain either one of these, not requiring the BODY_HERE absolutely.

**Comment by seanconklin** [comment] 2017-12-31 00:34
I've updated the http://make.beautomated.com site to v2.7 in development (set-up WP Pusher from GIT), so assigning for testing.

**Comment by randywsandberg** [comment] 2018-01-02 01:51
Could NOT reproduce this issue with the latest development BMEL plugin installed at make.beautomated.com. Closing as fixed.

**Closed by randywsandberg** 2018-01-02 01:51 UTC
Labels: bug
